### ISSUE TITLE
aiohttp-requests doesn't work with python 3.11

### ISSUE THREAD

**Issue by hf-kklein** [maxzheng/aiohttp-requests#8]
This is caused by: https://github.com/PyYoshi/cChardet/issues/81

In Python 3.11 I ran tox:

>   × Running setup.py install for cchardet did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      running install
      C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\util.py", line 212, in subst_vars
          return _subst_compat(s).format_map(lookup)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      KeyError: 'homedir'
      During handling of the above exception, another exception occurred:
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\KleinKonstantin\AppData\Local\Temp\pip-install-ys1zs43a\cchardet_cc1deee867f8447c8b0dde3dbb638242\setup.py", line 115, in <module>
          setup(
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\command\install.py", line 45, in finalize_options
          orig.install.finalize_options(self)
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\command\install.py", line 439, in finalize_options
          self.expand_basedirs()
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\command\install.py", line 619, in expand_basedirs
          self._expand_attrs(['install_base', 'install_platbase', 'root'])
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\command\install.py", line 613, in _expand_attrs
          val = subst_vars(val, self.config_vars)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\github\aiohttp-requests\{homedir}\.virtualenvs\aiohttp-requests\Lib\site-packages\setuptools\_distutils\util.py", line 214, in subst_vars
          raise ValueError(f"invalid variable {var}")
      ValueError: invalid variable 'homedir'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cchardet

**Comment by maxzheng** [comment]
Removed the dependency. Published 0.1.4 that works with 3.11 now.
